---

- name: Installation for Enterprise Linux OS
  include_tasks: enterprise_linux_OS_install.yml

- name: Generate and/or config the Nginx certs
  include_tasks: nginx_certs.yml

#- name: Configure the firewalld's configuration, mainly for testing purposes
#  include_tasks: firewall_config.yml

- name: Edit config files
  include_tasks: config.yml

- name: Launch Stream and its necessary services
  include_tasks: launching.yml
